# Generated by Django 4.1.3 on 2022-12-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuario_idtipo_bodeguero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idTipo_bodeguero',
            new_name='idTipo_bodeguero_id',
        ),
    ]
