# Generated by Django 4.1.3 on 2022-12-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_idtipo_bodeguero_usuario_idtipo_bodeguero_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idTipo_bodeguero_id',
            new_name='idTipo_bodeguero',
        ),
    ]
