# Generated by Django 4.1.3 on 2022-12-02 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_bodeguero',
            fields=[
                ('idTipo_bodeguero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_objeto',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_propietario', models.CharField(max_length=80)),
                ('apellido_propietario', models.CharField(max_length=80)),
                ('usuario', models.CharField(max_length=80, unique=True)),
                ('contrasena', models.CharField(max_length=60, unique=True)),
                ('idTipo_bodeguero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipo_bodeguero')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('idObjeto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('prestatario', models.CharField(blank=True, max_length=100)),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipo_objeto')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('idHistorico', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.TextField(blank=True)),
                ('accion', models.CharField(max_length=20)),
                ('modificado_por', models.CharField(max_length=80)),
                ('idObjeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objeto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
