# Generated by Django 4.1.3 on 2022-12-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuario_idtipo_bodeguero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='nombre_usuario',
        ),
    ]
